server:
  port: ${PORT}
bot:
  name: HappyBirthdayCongratulationsBot
  token: 1379206109:AAHuXjCEs52KvF6xxmVvvZODRwn8EE0YQh8
  notification:
    time: 14:00
proxy:
  enable: false
  host: 127.0.0.1
  port: 9150
  type: socks4
repository:
  type: mock
spring:
  profiles:
    active: dev
